### ISSUE TITLE
All these Dependencies?

### ISSUE THREAD

**Issue by dyardyGIT** [ardalis/AspNetCoreStartupServices#4]
Steve I was using an older listservices method from you.  Today, starting up asp.net core 3.1 application and came across this now nuget.

I went to install and the following dialog scared me.  I am currently building asp.net core 3.1 web application and your package wants to install the following dependencies...(even aspnetcore 1.1 dll's?)

Is this correct (it is going to reference all these other packages?)

![2019-12-16_15-10-10](https://user-images.githubusercontent.com/3586830/70939596-8d499300-2016-11ea-9039-663c66fc4371.png)

Web

Updates:

runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.0 -> runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.1
runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.0 -> runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.1
runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.0 -> runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.1
runtime.native.System.Security.Cryptography.OpenSsl.4.3.0 -> runtime.native.System.Security.Cryptography.OpenSsl.4.3.1
runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.0 -> runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.1
runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.0 -> runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.1
runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.0 -> runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.1
runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.0 -> runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.1
runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.0 -> runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.1
runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.0 -> runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.1
runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.0 -> runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.1
System.Net.Http.4.3.0 -> System.Net.Http.4.3.2

Installing:

Ardalis.ListStartupServices.1.1.3
Libuv.1.9.1
Microsoft.AspNetCore.1.1.0
Microsoft.AspNetCore.Diagnostics.1.1.0
Microsoft.AspNetCore.Diagnostics.Abstractions.1.1.0
Microsoft.AspNetCore.Hosting.1.1.0
Microsoft.AspNetCore.Http.1.1.0
Microsoft.AspNetCore.HttpOverrides.1.1.0
Microsoft.AspNetCore.Routing.1.1.0
Microsoft.AspNetCore.Routing.Abstractions.1.1.0
Microsoft.AspNetCore.Server.IISIntegration.1.1.0
Microsoft.AspNetCore.Server.Kestrel.1.1.0
Microsoft.CodeAnalysis.Analyzers.1.1.0
Microsoft.CodeAnalysis.Common.1.3.0
Microsoft.CodeAnalysis.CSharp.1.3.0
Microsoft.CodeAnalysis.VisualBasic.1.3.0
Microsoft.DiaSymReader.Native.1.4.1
Microsoft.Extensions.Configuration.EnvironmentVariables.1.1.0
Microsoft.Extensions.Logging.Console.1.1.0
Microsoft.Extensions.Options.ConfigurationExtensions.1.1.0
Microsoft.Extensions.PlatformAbstractions.1.1.0
Microsoft.NETCore.App.1.1.2
Microsoft.NETCore.DotNetHost.1.1.0
Microsoft.NETCore.DotNetHostPolicy.1.1.2
Microsoft.NETCore.DotNetHostResolver.1.1.0
Microsoft.NETCore.Jit.1.1.2
Microsoft.NETCore.Runtime.CoreCLR.1.1.2
Microsoft.NETCore.Windows.ApiSets.1.0.1
Microsoft.VisualBasic.10.1.0
runtime.native.System.Net.Security.4.3.0
System.Diagnostics.FileVersionInfo.4.0.0
System.Diagnostics.Process.4.3.0
System.Diagnostics.StackTrace.4.3.0
System.Dynamic.Runtime.4.3.0
System.IO.FileSystem.Watcher.4.3.0
System.IO.MemoryMappedFiles.4.3.0
System.IO.UnmanagedMemoryStream.4.3.0
System.Linq.Parallel.4.3.0
System.Linq.Queryable.4.3.0
System.Net.Requests.4.3.0
System.Net.Security.4.3.1
System.Net.WebHeaderCollection.4.3.0
System.Numerics.Vectors.4.3.0
System.Reflection.DispatchProxy.4.3.0
System.Reflection.Metadata.1.4.1
System.Resources.Reader.4.3.0
System.Runtime.Loader.4.3.0
System.Security.Claims.4.3.0
System.Threading.Overlapped.4.3.0
System.Threading.Tasks.Dataflow.4.7.0
System.Threading.Tasks.Parallel.4.3.0
System.Threading.Thread.4.3.0
System.Threading.ThreadPool.4.3.0
System.Xml.XPath.4.0.1
System.Xml.XPath.XDocument.4.0.1

**Comment by ardalis** [comment]
Fixed I think in the latest version. Open a new issue if not.
